// priority: 999
onEvent('item.tags', event => {
    event.add('mek1000:qio/t1', 'mekanism:inactive_qio_drive_base')
    event.add('mek1000:qio/t1', 'mekanism:qio_drive_base')
    event.add('mek1000:qio/t2', 'mekanism:inactive_qio_drive_hyper_dense')
    event.add('mek1000:qio/t2', 'mekanism:qio_drive_hyper_dense')
    event.add('mek1000:qio/t3', 'mekanism:inactive_qio_drive_time_dilating')
    event.add('mek1000:qio/t3', 'mekanism:qio_drive_time_dilating')
    event.add('mek1000:qio/t4', 'mekanism:inactive_qio_drive_supermassive')
    event.add('mek1000:qio/t4', 'mekanism:qio_drive_supermassive')
    event.add('mek1000:qio/t5', 'mekaevolution:inactive_qio_drive_absolute')
    event.add('mek1000:qio/t5', 'mekaevolution:qio_drive_absolute')
    event.add('mek1000:qio/t6', 'mekaevolution:inactive_qio_drive_supreme')
    event.add('mek1000:qio/t6', 'mekaevolution:qio_drive_supreme')
    event.add('mek1000:qio/t7', 'mekaevolution:inactive_qio_drive_cosmic')
    event.add('mek1000:qio/t7', 'mekaevolution:qio_drive_cosmic')
    event.add('mek1000:qio/t8', 'mekaevolution:inactive_qio_drive_infinite')
    event.add('mek1000:qio/t8', 'mekaevolution:qio_drive_infinite')
})